#!/bin/bash
echo "ALX"
echo -e "root@8aa5f7e54fd0:/alx-pre_course/0x01-git#"
printf
f
root@8aa5f7e54fd0:/alx-pre_course/0x0vi
it/bash# cat
root@8aa5f7e54fd0:/alx-pre_course/0x01-git/bash# cat > root@8aa5f7e54fd0:/alx-pre_course/0x01-git/bash#
df = df.root@8aa5f7e54fd0:/alx-pre_course/0x01-git/bash#
root@8aa5f7e54fd0:/alx-pre_course/0x01-git/bash# cd bash
git pull --rebase
